version: '3.8'
services:
  bot:
    build: .
    container_name: secrebot
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - ollama
  mongodb:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
volumes:
  mongo-data:
  ollama-data:
