export const CONFIG_DESCRIPTIONS = {
  'mongo.uri': 'URI de conexão com o MongoDB',
  'mongo.dbName': 'Nome do banco de dados',
  'mongo.collectionName': 'Coleção onde os lembretes são armazenados',
  'server.port': 'Porta do servidor web',
  'scheduler.interval': 'Intervalo (ms) para verificar agendamentos',
  'scheduler.maxAttempts': 'Tentativas máximas de envio de um lembrete',
  'scheduler.retryDelay': 'Atraso (ms) entre novas tentativas',
  'scheduler.concurrency': 'Número de envios simultâneos',
  'scheduler.dynamic.enabled': 'Ativa ajuste automático de concorrência',
  'scheduler.dynamic.min': 'Concorrência mínima dinâmica',
  'scheduler.dynamic.max': 'Concorrência máxima dinâmica',
  'scheduler.dynamic.cpuThreshold': 'Limite de uso de CPU para reduzir carga',
  'scheduler.dynamic.memThreshold': 'Limite de uso de memória para reduzir carga',
  'queues.llmConcurrency': 'Tarefas de IA em paralelo',
  'queues.whisperConcurrency': 'Processos de transcrição em paralelo',
  'queues.memoryThresholdGB': 'Memória (GB) para pausar filas',
  'queues.memoryCheckInterval': 'Intervalo (ms) de checagem de memória',
  'llm.model': 'Modelo de linguagem usado',
  'llm.imageModel': 'Modelo para visão computacional',
  'llm.maxTokens': 'Tokens máximos por resposta',
  'llm.host': 'Endereço do servidor Ollama',
  'audio.sampleRate': 'Taxa de amostragem do áudio',
  'audio.model': 'Modelo Whisper',
  'audio.language': 'Idioma padrão das transcrições',
  'audio.timeoutMs': 'Timeout da transcrição (ms)',
  'elevenlabs.apiKey': 'Chave da API ElevenLabs',
  'elevenlabs.voiceId': 'ID de voz ElevenLabs',
  'elevenlabs.modelId': 'Modelo de TTS ElevenLabs',
  'elevenlabs.stability': 'Estabilidade da voz',
  'elevenlabs.similarityBoost': 'Similaridade da voz',
  'piper.enabled': 'Ativa TTS local Piper',
  'piper.executable': 'Executável do Piper',
  'piper.model': 'Modelo do Piper',
  'calorieApi.url': 'URL da API de calorias',
  'calorieApi.key': 'Chave da API de calorias',
  'google.clientId': 'Client ID do Google',
  'google.clientSecret': 'Client Secret do Google',
  'google.redirect': 'URL de redirecionamento OAuth',
  'linkedin.user': 'Usuário do LinkedIn',
  'linkedin.pass': 'Senha do LinkedIn',
  'linkedin.liAt': 'Cookie li_at',
  'linkedin.timeoutMs': 'Timeout do LinkedIn (ms)'
};

export const CONFIG_ENV_MAP = {
  'mongo.uri': 'MONGO_URI',
  'server.port': 'PORT',
  'scheduler.interval': 'SCHED_INTERVAL',
  'scheduler.maxAttempts': 'SCHED_MAX_ATTEMPTS',
  'scheduler.retryDelay': 'SCHED_RETRY_DELAY',
  'scheduler.concurrency': 'SCHED_CONCURRENCY',
  'scheduler.dynamic.enabled': 'DYNAMIC_CONCURRENCY',
  'scheduler.dynamic.min': 'SCHED_DYNAMIC_MIN',
  'scheduler.dynamic.max': 'SCHED_MAX_CONCURRENCY',
  'scheduler.dynamic.cpuThreshold': 'SCHED_CPU_THRESHOLD',
  'scheduler.dynamic.memThreshold': 'SCHED_MEM_THRESHOLD',
  'queues.llmConcurrency': 'LLM_CONCURRENCY',
  'queues.whisperConcurrency': 'WHISPER_CONCURRENCY',
  'queues.memoryThresholdGB': 'QUEUE_MEM_THRESHOLD_GB',
  'queues.memoryCheckInterval': 'MEM_CHECK_INTERVAL',
  'llm.model': 'LLM_MODEL',
  'llm.imageModel': 'LLM_IMAGE_MODEL',
  'llm.maxTokens': 'LLM_MAX_TOKENS',
  'llm.host': 'OLLAMA_HOST',
  'audio.sampleRate': 'AUDIO_SAMPLE_RATE',
  'audio.model': 'WHISPER_MODEL',
  'audio.language': 'AUDIO_LANGUAGE',
  'audio.timeoutMs': 'WHISPER_TIMEOUT_MS',
  'elevenlabs.apiKey': 'ELEVENLABS_API_KEY',
  'elevenlabs.voiceId': 'ELEVENLABS_VOICE_ID',
  'elevenlabs.modelId': 'ELEVENLABS_MODEL_ID',
  'elevenlabs.stability': 'ELEVENLABS_STABILITY',
  'elevenlabs.similarityBoost': 'ELEVENLABS_SIMILARITY',
  'piper.enabled': 'PIPER_ENABLED',
  'piper.executable': 'PIPER_EXECUTABLE',
  'piper.model': 'PIPER_MODEL',
  'calorieApi.url': 'CALORIE_API_URL',
  'calorieApi.key': 'CALORIE_API_KEY',
  'google.clientId': 'GOOGLE_CLIENT_ID',
  'google.clientSecret': 'GOOGLE_CLIENT_SECRET',
  'google.redirect': 'GOOGLE_REDIRECT',
  'linkedin.user': 'LINKEDIN_USER',
  'linkedin.pass': 'LINKEDIN_PASS',
  'linkedin.liAt': 'LINKEDIN_LI_AT',
  'linkedin.timeoutMs': 'LINKEDIN_TIMEOUT_MS'
};